# Generated by Django 5.0.6 on 2024-06-25 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createblog',
            name='publish_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
